### ISSUE TITLE
Windows Admin Center on DC ?

### ISSUE THREAD

**Issue by johnhhaines** [bfrankMS/CreateHypervVms#10]
In Step 6 of the "CreateVmsUsingScript" documentation, you state:

"Windows Admin Center is installed locally at https://localhost/"

But WAC won't install onto a DC - I know the MSI file can be modifed to do so, is this what we need to do ?

**Comment by bfrankMS** [comment]
Hi 

it is as easy as:
1st install WAC
2nd run adprep i.e. create domain.
---> WAC can run on a DC / no need to change .msi file. :-)
hth,
B

**Comment by johnhhaines** [comment]
So you are saying install WAC before I promote the server to a DC... But the install script does all of that without any opportunity to interact with the server before it becomes a DC, doesn't it ?

**Comment by bfrankMS** [comment]
The scripts will (should do this) for you automatically. :-)
Here is how it works:
- The config in 3_PostInstallScripts.psd1
https://github.com/bfrankMS/CreateHypervVms/blob/master/Scenario-AzStackHCI/3_PostInstallScripts.psd1
defines the order (alphabetical)
![image](https://github.com/user-attachments/assets/55199523-a0dc-4879-b726-ffd3e1f9c444)
the PS script step_PrepareAdminBox.ps1 has a section to install WAC.
![image](https://github.com/user-attachments/assets/0486c708-5305-4522-85f8-f7f4887745be)
the Domain is created in a later step.
