### ISSUE TITLE
Routing and Remote Access Issue

### ISSUE THREAD

**Issue by jpcapone** [bfrankMS/CreateHypervVms#4]
I have deployed the stack several times (probably more) and I keep running into the same issue.  The first symptom is that the HCI servers cannot ping externally.  The DNS names resolve as expected but no ping responses and internet access is not available from the HCI stack server.  I am able to ping the DC from each node but the nodes can't ping each other.  
When i attempt to access the routing and remote access console on the DC i get the error below.  
![image](https://github.com/bfrankMS/CreateHypervVms/assets/47680328/bc806891-c961-4e72-bbb5-d475fd645087)

I would think that the NICS connected to the internal switch would allow the nodes to talk with each other and maybe its the firewall thats blocking icmp between the nodes.  Either way there seems to be an issue with Routing and Remote Access on the DC.  I can think of ways to work around this but I wanted to share my findings with everyone and see if anyone else experiences this issue.  I want to use the resources provided in this repo and not deviate by making the changes I think would work so that I can walk thru the entire video.  I am using pretty much everything listed in the video from the images to the folder locations down to the network ranges.
![image](https://github.com/bfrankMS/CreateHypervVms/assets/47680328/668af7a1-4cc2-4994-91db-6a31806fad4e)

Any suggestions would be appreciated.

EDIT: I uninstalled the Routing and Remote Access service, reinstalled it and now I am able to ping internet addresses from the stack nodes!

**Comment by bfrankMS** [comment]
Hi @jpcapone 
apologies for not getting back to you earlier. Others have reported sporadic issues with RRAS not being setup correctly. Maybe some timings are wrong. 
Unfortunately I cannot reproduce the error. The file "C:\temp\netshfile.txt" on the DC is taken to automate the install of the RRAS service. But you have done the best thing until I'll be able to reproduce and find the time to TS.
thx for posting this.
B
