### ISSUE TITLE
Minor issue with NAT setup on DC

### ISSUE THREAD

**Issue by heinejeppesen** [bfrankMS/CreateHypervVms#7]
Hi,

Thanks for creating this framework, allowing me to easily try out Azure Stack HCI ;-)

I couldn't get the network traffic flowing from the two HCI hosts, so I did a little digging around to make it work.

In "step_PrepareAdminbox.ps1" in line 46 / 47 is says:
_add interface name="EXTERNAL" mode=FULL
add interface name="INTERNAL" mode=PRIVATE_

But the network interfaces are called "EXT" and "aMGMT" in the setup generated with the scripts.

So replacing with: 
_add interface name="EXT" mode=FULL
add interface name="aMGMT" mode=PRIVATE_

or just running the commands like this after starting NetSH.exe as admin on the DC.
_pushd routing ip nat
add interface name="EXT" mode=FULL
add interface name="aMGMT" mode=PRIVATE_

NAT immediately started working from the HCI nodes, after doing so.
Hopefully this can be changed in the repo or help others trying the framework out.

**Comment by fareedhayat1** [comment]
Hi @heinejeppesen,
can you please help me out with the IP configurations in file 3_postinstallscript. should i get the ipconfig of the host vm and add them accordingly their or what should i do. Currently i got the IP for external switch and staying in that range entered the IP address and for the default gateway kept it same as the external switch in the ipconfig in host VM. but it doesnt allow any of the VMs to get response back from ping ibm.com command. Actually the VMs doesnt show any internet connectivity as well.
Looking forward to see your response @heinejeppesen.
Thankyou

**Comment by heinejeppesen** [comment]
Are you asking about what to put in ScriptArguments in line 12? 

It's the subnet your Azure Stack infrastructure run on and IP addresses for DNS servers to resolve addresses externally.
I just use Cloudflare's 1.1.1.1 or Google's 8.8.8.8 for external DNS when playing around with something.
Which subnet to specify only you can know, since it's on your network.

And please don't hijack existing threads for unrelated questions.

**Comment by bfrankMS** [comment]
> Hi,
> 
> Thanks for creating this framework, allowing me to easily try out Azure Stack HCI ;-)
> 
> I couldn't get the network traffic flowing from the two HCI hosts, so I did a little digging around to make it work.
> 
> In "step_PrepareAdminbox.ps1" in line 46 / 47 is says: _add interface name="EXTERNAL" mode=FULL add interface name="INTERNAL" mode=PRIVATE_
> 
> But the network interfaces are called "EXT" and "aMGMT" in the setup generated with the scripts.
> 
> So replacing with: _add interface name="EXT" mode=FULL add interface name="aMGMT" mode=PRIVATE_
> 
> or just running the commands like this after starting NetSH.exe as admin on the DC. _pushd routing ip nat add interface name="EXT" mode=FULL add interface name="aMGMT" mode=PRIVATE_
> 
> NAT immediately started working from the HCI nodes, after doing so. Hopefully this can be changed in the repo or help others trying the framework out.

Hi,

thanks for posting this however IMHO this should not be required as the strings "EXTERNAL" and "INTERNAL" should be replaced using parameters passed in - see lines 51,52:
$netshFile = $netshFile -replace "EXTERNAL",$externalAdapterName
$netshFile = $netshFile -replace "INTERNAL",$internalAdapterName

but you are right some folks reported issues with the RRAS setup - so I might justify investigating for a more robust setup.

thx,
B

**Comment by bfrankMS** [comment]
> Are you asking about what to put in ScriptArguments in line 12?
> 
> It's the subnet your Azure Stack infrastructure run on and IP addresses for DNS servers to resolve addresses externally. I just use Cloudflare's 1.1.1.1 or Google's 8.8.8.8 for external DNS when playing around with something. Which subnet to specify only you can know, since it's on your network.
> 
> And please don't hijack existing threads for unrelated questions.

Yeah - have a look a the picture in 
[https://github.com/bfrankMS/CreateHypervVms/blob/master/Scenario-AzStackHCI/docs/overview.png](https://github.com/bfrankMS/CreateHypervVms/blob/master/Scenario-AzStackHCI/docs/overview.png)
it explains the values I used. 
-> you need to tweak the settings to your system to give the DC an IP for it's Ext(ernal) adapter that is valid on YOUR network and choose whatever upstream DNS server that is valid for you ;-)
